M48
; DRILL file KiCad 10.0.4 date 2026-07-10T01:05:18
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-10T01:05:18+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.100
%
G90
G05
T1
X108.777Y-82.233
T2
X178.542Y-122.42
X184.322Y-122.42
T3
X134.028Y-86.58
M30
